# Site
name: 'Whales of Heaven'
description: 'exploring the intersection of everyday life and faith'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''
disqus: ''
email: 'whalesofheaven@gmail.com'
mailchimp-list: '' #'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
formspree: mwkwzagj

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    elijah:
      name:           Elijah
      site:           https://sites.google.com/view/elijahslee
      avatar:         assets/images/elijah.jpeg
      bio:            "Hi, I'm Elijah, and I like drones."
      email:          elijahslee@gmail.com
      twitter:        https://twitter.com/elijah4rain

    paul:
      name:           Paul
      site:           https://whalesofheaven.com
      avatar:         assets/images/paul.jpeg
      bio:            "Hi, I'm Paul, and I like to play soccer."
      email:          fakemail@gmail.com
      twitter:        https://twitter.com/whalesofheaven
    
    kevin:
      name:           Kevin
      site:           https://www.wowthemes.net
      avatar:         assets/images/kevin.jpeg
      bio:            "Hi, I'm Kevin, and I cure blindness."
      email:          fakemail@gmail.com
      twitter:        https://twitter.com/whalesofheaven
    
    harang:
      name:           harang
      site:           https://harangju.com
      avatar:         assets/images/harang.jpg
      bio:            "Hi, I'm Harang."
      email:          harangju@gmail.com
      twitter:        https://twitter.com/harangju
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: sal
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
