# Site
name: 'Whales of Heaven'
description: 'exploring the intersection of everyday life and faith'
logo: 'assets/images/icon.png'
logo-og: 'assets/images/icon-og.png'
favicon: 'assets/images/icon.png'
baseurl: ''
disqus: ''
email: 'whalesofheaven@gmail.com'
mailchimp-list: 'https://whalesofheaven.us1.list-manage.com/subscribe/post?u=b7e34bf4ae83abc87f01b2127&amp;id=9464ef67f8'
formspree: mwkwzagj

include: ["_pages"]
permalink: /:title/

collections:
  mannas:
  newsletters:
    output: True

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

authors:
    elijah:
      name:           Elijah
      site:           https://sites.google.com/view/elijahslee
      avatar:         assets/images/elijah.jpeg
      bio:            "Hi, I'm Elijah, and I research drones."
      email:          elijahslee@gmail.com
      twitter:        https://twitter.com/elijah4rain

    paul:
      name:           Paul
      site:           https://whalesofheaven.com
      avatar:         assets/images/paul.jpeg
      bio:            "Hi, I'm Paul, and I am free."
      email:          fakemail@gmail.com
      twitter:        https://twitter.com/whalesofheaven

    kevin:
      name:           Kevin
      site:           https://www.wowthemes.net
      avatar:         assets/images/kevin.jpeg
      bio:            "Hi, I'm Kevin, and I research biotech."
      email:          fakemail@gmail.com
      twitter:        https://twitter.com/whalesofheaven

    harang:
      name:           harang
      site:           https://harangju.com
      avatar:         assets/images/harang.jpg
      bio:            "Hi, I'm Harang, and I research neurons."
      email:          harangju@gmail.com
      twitter:        https://twitter.com/harangju

# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: sal
      avatar: /assets/images/avatar1.jpg

  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page

# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
